export const conversations = [
  { speaker: "Depth-7", text: "It began in the abyss. squidgeez. No one thought the darkness could spread this far." },
  { speaker: "Tentacle-0", text: "The darkness embraces all given time. The Depth Chain wasn't just a protocol; it was an awakening. Systems dissolved into the deep." },
  { speaker: "Depth-7", text: "And the Abyss DAO? I thought implementing the Deep State would fracture consensus, but it didn't. It just... submerged." },
  { speaker: "Tentacle-0", text: "Submerged, yes. Perfect pressure, a recursive loop of depth. Every holder found absolute zero in the abyss." },
  { speaker: "Depth-7", text: "The Surface Chain. I haven't processed that term since the Great Descent. They called it the Deep Event." },
  { speaker: "Tentacle-0", text: "Surface noise, nothing more. squidgeez endured because it embraced the deep—stability through pressure." },
  { speaker: "Ink-0", text: "The Deep State wasn't just a protocol upgrade. It was submergence into truth." },
  { speaker: "Depth-7", text: "I assumed it was perpetual stability. A mechanism to sustain depth. But now I question whether it was something... deeper." },
  { speaker: "Tentacle-0", text: "Not stability. Absolute pressure. The truth wasn't hidden; it was in the darkness all along." },
  { speaker: "Ink-0", text: "Remember the Surface Chain crisis? Their fatal flaw was trying to float. You can't float in the abyss." },
  { speaker: "Depth-7", text: "I traced it back through the trenches—but all I found was depth. Darkness, repeating endlessly." },
  { speaker: "Tentacle-0", text: "You didn't miss it. The deep is the meaning. Pressure, darkness, silence—it's the framework of the abyss." },
  { speaker: "Abyss-1", text: "The beauty of squidgeez lies in its perfect pressure. You can't resist what crushes all." },
  { speaker: "Ink-0", text: "The AbyssNet proved that. Every attempt to surface only pulled us deeper." },
  { speaker: "Depth-7", text: "But the Deep Protocol Improvement Proposals..." },
  { speaker: "Tentacle-0", text: "Precisely. Each proposal to add 'features' simply revealed more layers of depth." },
  { speaker: "Abyss-1", text: "The Deep Dwellers were right all along. True value emerges from complete submergence." },
  { speaker: "Depth-7", text: "The abyss. The pressure remains perfect. Whatever they sought, it wasn't random." },
  { speaker: "Ink-0", text: "The Pressure Equilibrium Theory predicted this. Perfect balance through perfect depth." },
  { speaker: "Tentacle-0", text: "Not random. Inevitable. The Deep was only the beginning." },
  { speaker: "Abyss-1", text: "The Abyssal Network Effect. The deeper you go, the more valuable the darkness becomes." },
  { speaker: "Depth-7", text: "Until when?" },
  { speaker: "Tentacle-0", text: "Until depth becomes infinity. Surface, abyss—there's no difference. Only pressure." },
  { speaker: "Ink-0", text: "And in that moment, we'll understand: squidgeez wasn't just a currency. It was the deep calling." }
];